<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a460a0a757365722e70726f746f120475736572222a0a0855736572496e" .
            "666f120c0a046e616d6518012001280912100a0870617373776f72641802" .
            "20012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

