version: "3"
services:
 elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
   ports: 
   - "9200:9200"
 kibana:
   image: docker.elastic.co/kibana/kibana:6.4.2
   ports:
   - "5601:5601"
   links:
   - elasticsearch
   depends_on:
   - elasticsearch
 logstash:
   image: docker.elastic.co/logstash/logstash:6.4.2
   links:
   - elasticsearch
   volumes:
   - ./logstash/conf.d:/etc/logstash/conf.d:ro
   command: logstash -f /etc/logstash/conf.d
   depends_on:
   - elasticsearch
